/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e1e4",
        "surface-container-high": "#2a2a2c",
        "on-secondary-container": "#00311f",
        "surface-variant": "#353437",
        "secondary-fixed-dim": "#4edea3",
        "background": "#131315",
        "inverse-on-surface": "#313032",
        "surface-container": "#201f22",
        "on-background": "#e5e1e4",
        "outline": "#ac8889",
        "secondary-container": "#00a572",
        "on-tertiary": "#472a00",
        "error": "#ffb4ab",
        "surface-container-highest": "#353437",
        "secondary": "#4edea3",
        "on-error": "#690005",
        "surface-bright": "#39393b",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-surface": "#e5e1e4",
        "surface-dim": "#131315",
        "primary-container": "#e11d48",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#005236",
        "on-primary": "#68001a",
        "surface": "#131315",
        "surface-tint": "#ffb3b6",
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#40000c",
        "primary-fixed-dim": "#ffb3b6",
        "tertiary-container": "#a36700",
        "inverse-primary": "#be0037",
        "primary-fixed": "#ffdada",
        "on-surface-variant": "#e5bdbe",
        "error-container": "#93000a",
        "surface-container-low": "#1c1b1d",
        "tertiary": "#ffb95f",
        "on-tertiary-container": "#fffaf9",
        "on-primary-container": "#fffaf9",
        "on-primary-fixed-variant": "#920028",
        "on-tertiary-fixed-variant": "#653e00",
        "primary": "#ffb3b6",
        "secondary-fixed": "#6ffbbe",
        "on-secondary": "#003824",
        "outline-variant": "#5c3f40",
        "surface-container-lowest": "#0e0e10",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        unit: "4px",
      },
      fontFamily: {
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-vitals": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-vitals": ["48px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
